### ISSUE TITLE
Issue getting results.sarif file after scan

### ISSUE THREAD

**Issue by vidhya03** [Contrast-Security-OSS/contrastscan-action#29]
Scan is done however , file generation is not completed. 
```
      - name: Run SAST scan        
        uses: Contrast-Security-OSS/contrastscan-action@v3.0.2
        with:
          projectName: myapp
          artifact: source-artifact.zip
          apiUrl: https://app.contrastsecurity.com
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          fail: false

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
```

do we need to pass arguments , i see in the log 
`Use contrast scan --save to save results as a SARIF
`
